peridot: Remove duplicate modem_firmware symlink and switch to common
Causing error duplicate modules after merging QPR2, we try to drop it

error: build/soong/fsgen/Android.bp:31:1: module "lineage_peridot_generated_vendor_image" variant "android_common" (created by module "soong_filesystem_creator" variant "android_common"): packaging conflict at rfs/msm/mpss/readonly/firmware:
{rfs/msm/mpss/readonly/firmware <nil> /vendor/modem_firmware false <nil> vendor false 0xc3c6a093c0 {common  } 0xc3c63ff2d8 rfs_msm_mpss_readonly_modem_firmware_symlink}
{rfs/msm/mpss/readonly/firmware <nil> /vendor/firmware_mnt false <nil> vendor false 0xc3c5f9abc0 {common  } 0xc3c5ae3860 rfs_msm_mpss_readonly_firmware_symlink}
error: build/soong/fsgen/Android.bp:31:1: module "lineage_peridot_generated_vendor_image" variant "android_common" (created by module "soong_filesystem_creator" variant "android_common"): packaging conflict at rfs/msm/mpss/readonly/firmware:
{rfs/msm/mpss/readonly/firmware <nil> /vendor/modem_firmware false <nil> vendor false 0xc3c6a093c0 {common  } 0xc3c63ff2d8 rfs_msm_mpss_readonly_modem_firmware_symlink}
{rfs/msm/mpss/readonly/firmware <nil> /vendor/firmware_mnt false <nil> vendor false 0xc3c5f9abc0 {common  } 0xc3c5ae3860 rfs_msm_mpss_readonly_firmware_symlink}

Signed-off-by: Drenzzz <realdrenzzz@gmail.com>